### ISSUE TITLE
Issues with Program Reproduction and Usage

### ISSUE THREAD

**Issue by AllenJHawk** [JK-the-Ko/Self2SelfPlus#1]
Dear Author,
I am a student studying image processing. I have recently read your article, downloaded the associated code, and attempted to reproduce the results. I have a rather naive question. I was successful in removing noise from the airplane images in the sigma25 folder of the CBSD68 dataset. However, when I replaced the airplane images with my own noisy images, the denoising was unsuccessful. I used the same path and the same denoising process and method, but I could not achieve the same denoising results. I am unsure about the reason behind this. I sincerely hope you could provide an answer! Thank you!

**Comment by JK-the-Ko** [comment]
Hello,

As stated in the paper, the probability for the Bernoulli sampling & dropout and number of iterations vary.

Hence, you should find an appropriate hyperparameter for your own dataset.

Thank you.

**Comment by AllenJHawk** [comment]
Thank you for your reply. I will further study the issue with the hyperparameters, and once again thank you for your paper!

**Comment by AllenJHawk** [comment]
Dear ediotr:

I confirm that this email can contact me and i am one of the co-authors of article of jmse-2664592.

Chao Jiang
best wishes

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jaekyun Ko ***@***.***>
发送时间: Tuesday, October 24, 2023 3:53:24 PM
收件人: JK-the-Ko/Self2SelfPlus ***@***.***>
抄送: AllenJHawk ***@***.***>; Author ***@***.***>
主题: Re: [JK-the-Ko/Self2SelfPlus] Issues with Program Reproduction and Usage (Issue #1)


Hello,

As stated in the paper, the probability for the Bernoulli sampling & dropout and number of iterations vary.

Hence, you should find an appropriate hyperparameter for your own dataset.

Thank you.

―

**Comment by AllenJHawk** [comment]
I'm sorry, I sent the wrong email. Haha, it's embarrassing.🤣

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 蒋 超 ***@***.***>
发送时间: Tuesday, October 24, 2023 6:32:03 PM
收件人: JK-the-Ko/Self2SelfPlus ***@***.***>; JK-the-Ko/Self2SelfPlus ***@***.***>
抄送: Author ***@***.***>
主题: Re: [JK-the-Ko/Self2SelfPlus] Issues with Program Reproduction and Usage (Issue #1)

Dear ediotr:

I confirm that this email can contact me and i am one of the co-authors of article of jmse-2664592.

Chao Jiang
best wishes

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jaekyun Ko ***@***.***>
发送时间: Tuesday, October 24, 2023 3:53:24 PM
收件人: JK-the-Ko/Self2SelfPlus ***@***.***>
抄送: AllenJHawk ***@***.***>; Author ***@***.***>
主题: Re: [JK-the-Ko/Self2SelfPlus] Issues with Program Reproduction and Usage (Issue #1)


Hello,

As stated in the paper, the probability for the Bernoulli sampling & dropout and number of iterations vary.

Hence, you should find an appropriate hyperparameter for your own dataset.

Thank you.
